services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: # TODO: Create directory/volume on your machine
      - "postgres_volume:/var/lib/postgresql/data"
    ports: # TODO: Set other port on the left if it's already used on your machine
      - "5432:5432"
    container_name: postgres
volumes:
  postgres_volume:
  # external: true